<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An Exploratory Analysis Delving into the Complex Relationship Between Race, Socioeconomic, and Post-Grad Earnings">

<title>Analysis – MA [46]15 Final Project Group 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA [46]15 Final Project Group 3</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html"> 
<span class="menu-text">Does the American Dream Exist in Higher Education?</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivation-behind-data-analysis" id="toc-motivation-behind-data-analysis" class="nav-link active" data-scroll-target="#motivation-behind-data-analysis">Motivation Behind Data Analysis</a></li>
  <li><a href="#key-questions" id="toc-key-questions" class="nav-link" data-scroll-target="#key-questions">Key Questions</a></li>
  <li><a href="#linear-model-of-racial-disparity-in-post-graduation-earnings" id="toc-linear-model-of-racial-disparity-in-post-graduation-earnings" class="nav-link" data-scroll-target="#linear-model-of-racial-disparity-in-post-graduation-earnings">Linear Model of Racial Disparity in Post-Graduation Earnings</a></li>
  <li><a href="#residual-plots-for-the-first-model" id="toc-residual-plots-for-the-first-model" class="nav-link" data-scroll-target="#residual-plots-for-the-first-model">Residual Plots for The First Model</a></li>
  <li><a href="#linear-model-of-racial-disparities-in-post-graduation-earnings-after-adding-a-socioeconomic-factor" id="toc-linear-model-of-racial-disparities-in-post-graduation-earnings-after-adding-a-socioeconomic-factor" class="nav-link" data-scroll-target="#linear-model-of-racial-disparities-in-post-graduation-earnings-after-adding-a-socioeconomic-factor">Linear Model of Racial Disparities in Post-Graduation Earnings After Adding a Socioeconomic Factor</a>
  <ul class="collapse">
  <li><a href="#model-findings-1" id="toc-model-findings-1" class="nav-link" data-scroll-target="#model-findings-1">Model Findings</a></li>
  </ul></li>
  <li><a href="#a-second-dataset-what-does-the-sat-really-test" id="toc-a-second-dataset-what-does-the-sat-really-test" class="nav-link" data-scroll-target="#a-second-dataset-what-does-the-sat-really-test">A Second Dataset: What does the SAT really test?</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    An Exploratory Analysis Delving into the Complex Relationship Between Race, Socioeconomic, and Post-Grad Earnings
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="images/analysis-pic.jpg" class="img-fluid"></p>
<section id="motivation-behind-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="motivation-behind-data-analysis">Motivation Behind Data Analysis</h2>
<p>This analysis is motivated by the need to unravel how racial disparity adversely impacts different groups across the United States. Continuing to question societal norms and reveal how inequities persist in society is crucial towards challenging prejudice and racism.</p>
<section id="variables-and-relationships-of-interest" class="level4">
<h4 class="anchored" data-anchor-id="variables-and-relationships-of-interest">Variables and Relationships of Interest</h4>
<p>This analysis aims to investigate the relationship between mean post-graduation earnings, a post-college academic indicator of success, with student characteristics of race and socioeconomic status. By identifying if there exists a correlation between specific student characteristics and pre-college factors with post-college success outcomes, the analysis aims to provide insight on whether financial success is related to race and before-college-affluence.</p>
<p><img src="images/divide.jpg" class="img-fluid"></p>
<p><em>The following variables from the dataset will be the focal point in the analysis:</em></p>
<p>Every school has varying student populations and proportion students from each race category. To ensure the consistency of the data, this analysis utilizes weighted average earnings:</p>
<ul>
<li><strong>Num_White_Students:</strong> Number of White students at the institution</li>
<li><strong>Num_Black_Students:</strong> Number of Black students at the institution</li>
<li><strong>Num_Hispanic_Students:</strong> Number of Hispanic students at the institution</li>
<li><strong>Num_Asian_Students:</strong> Number of Asian students in at the institution</li>
<li><strong>Social_Econ_Div:</strong> <em>(For a more detailed explanation, see <code>Big Picture</code> page)</em> Proportion undergraduate students who received Pell Grants, displaying a metric for low income student population</li>
</ul>
<p><em>The key questions are as followed:</em></p>
</section>
</section>
<section id="key-questions" class="level2">
<h2 class="anchored" data-anchor-id="key-questions">Key Questions</h2>
<p><em>The key questions are as followed:</em></p>
<section id="i.-do-historically-black-colleges-and-universities-hbcus-have-significantly-lower-average-post-graduation-earnings-compared-to-non-hbcus" class="level5">
<h5 class="anchored" data-anchor-id="i.-do-historically-black-colleges-and-universities-hbcus-have-significantly-lower-average-post-graduation-earnings-compared-to-non-hbcus">I. Do Historically Black Colleges and Universities (HBCUs) have significantly lower average post-graduation earnings compared to non-HBCUs?</h5>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <strong>Welch Two Sample t-test</strong> results indicate a statistically significant difference in post-graduation earnings between HBCU and non-HBCU graduates <em>(p-value = 5.09e-08)</em>. The mean earnings for HBCU graduates <em>($30,646.67)</em> are significantly lower than those of non-HBCU graduates <em>($46,492.66)</em>. The 95% confidence interval for the difference in means ranges from -18,530.66 to -13,161.34, confirming that HBCU graduates earn considerably less, on average, than their non-HBCU counterparts. This result supports the idea that there exist a significant earnings gap between HBCUs and non-HBCUs.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  hbcu_earnings and non_hbcu_earnings
t = -12.99, df = 11.008, p-value = 5.09e-08
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -18530.66 -13161.34
sample estimates:
mean of x mean of y 
 30646.67  46492.66 </code></pre>
</div>
</div>
</section>
<section id="ii.-is-there-a-significant-difference-in-post-graduation-earnings-between-racial-groups-across-u.s.-colleges" class="level5">
<h5 class="anchored" data-anchor-id="ii.-is-there-a-significant-difference-in-post-graduation-earnings-between-racial-groups-across-u.s.-colleges">II. Is there a significant difference in post-graduation earnings between racial groups across U.S. colleges?</h5>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplots illustrate the relationship between the number of students belonging to each racial group and average post-graduation earnings across U.S. colleges. This suggests that there does exist a relationship between racial composition and earnings differs across different racial groups:</p>
<ol type="1">
<li><strong>Asian Students:</strong> There is a positive correlation between the number of Asian students and average earnings, indicating that colleges with more Asian students tend to have higher average post-graduation earnings.</li>
<li><strong>Black Students:</strong> There is a negative correlation between the number of Black students and average earnings, indicating that colleges with more Black students tend to have lower average post-graduation earnings.</li>
<li><strong>White Students:</strong> There is a positive correlation between the number of White students and average earnings, indicating that colleges with more White students tend to have higher average post-graduation earnings.</li>
<li><strong>Hispanic Students:</strong> There is a positive correlation between number of Hispanic students and average earnings, but the best-fit line is less steep than for their Asian and White counterparts.</li>
</ol>
<p>These plots highlight the disparity in post-graduation earnings across racial groups, with Asian and White students exhibiting higher earnings, on average, than Black and Hispanic students. Further statistical experimentation and tests would be necessary to draw claims about causality.</p>
</section>
</section>
<section id="linear-model-of-racial-disparity-in-post-graduation-earnings" class="level2">
<h2 class="anchored" data-anchor-id="linear-model-of-racial-disparity-in-post-graduation-earnings">Linear Model of Racial Disparity in Post-Graduation Earnings</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients, Standard Errors and p-values:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                           Estimate   Std. Error      Pr(&gt;|t|)
(Intercept)           44723.0033897 573.50947741 8.295763e-290
Num_White_Students        0.1675265   0.08495377  4.914026e-02
Num_Black_Students       -0.9476908   0.35300530  7.491702e-03
Num_Hispanic_Students    -0.3944273   0.17099896  2.146745e-02
Num_Asian_Students        2.2823179   0.27884623  2.099718e-15</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
R-squared:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Multiple R-squared: 0.1393846 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Adjusted R-squared: 0.1327898 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
F-statistic and p-value:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>F-statistic: 21.13567 on 4 and 522 DF, p-value: 3.612555e-16 </code></pre>
</div>
</div>
<section id="model-overview" class="level4">
<h4 class="anchored" data-anchor-id="model-overview">Model Overview:</h4>
<p>For this model, every race variable from the <code>education_cohort_data_cleaned</code> dataset is being included in order to build a simple linear regression. It displays the change in median earnings as a function of racial composition change, with no other factors included.</p>
</section>
<section id="model-findings" class="level4">
<h4 class="anchored" data-anchor-id="model-findings">Model Findings:</h4>
<p><strong>Num_White_Students:</strong> A one White student increase in a school is associated with a $0.168 increase in the expected value of mean post-grad earnings of students, but it is not significant <em>(p = 0.947)</em>.</p>
<p><strong>Num_Black_Students:</strong> A one Black student increase in a school is associated with a $0.948 decrease in the expected value of mean post-grad earnings of students, and it is significant <em>(p = 0.007)</em>.</p>
<p><strong>Num_Asian_Students:</strong> A one Asian student increase in a school is associated with a $2.282 increase in the expected value of mean post-grad earnings of students, and it is highly significant <em>(p &lt; 0.001)</em>.</p>
<p><strong>Num_Hispanic_Students:</strong> A one Hispanic student increase in a school is associated with a $0.394 decrease in the expected value of mean post-grad earnings of students, and it is significant <em>(p = 0.0147)</em>.</p>
<p>The adjusted R-square value of <strong>0.1328</strong> shows that approximately 13.28% of the variation in median earnings within schools is explained by the model, indicating the model has only a small portion of explanatory power.</p>
<p>The findings from this regression model show disparity in mean earnings after graduating based on the racial composition of undergraduate students. Specifically, schools with higher percentages of Black students are associated with lower earnings. On the other hand, a higher proportion of Asian students is strongly correlated to higher earnings. However, the low number of adjusted R-square is a sign of omitted variable bias. The model could be improved by adding some control variables. including economic and institutional factors.</p>
</section>
</section>
<section id="residual-plots-for-the-first-model" class="level2">
<h2 class="anchored" data-anchor-id="residual-plots-for-the-first-model">Residual Plots for The First Model</h2>
<p>Residual Plots help to determine whether a linear model is appropriate in modeling.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Asian students:</strong> The residuals show a tighter cluster around zero at lower percentages of Asian students, but as percentage increases, exhibits increasing variability.</li>
<li><strong>Black students:</strong> The residuals are concentrated more closer near zero at lower percentages of Black students, but spread out at higher percentages.</li>
<li><strong>Hispanic students:</strong> The residuals are mostly centered around zero at lower percentages of Hispanic students, but show greater variability as the proportion increases.</li>
<li><strong>White students:</strong> The residuals display less variability and appear more evenly distributed across the range of percentages compared to other groups.</li>
</ul>
<p>These residual plots indicate heteroskedasticity, where the variance of residuals is not constant across the predictor variable.</p>
</section>
<section id="linear-model-of-racial-disparities-in-post-graduation-earnings-after-adding-a-socioeconomic-factor" class="level2">
<h2 class="anchored" data-anchor-id="linear-model-of-racial-disparities-in-post-graduation-earnings-after-adding-a-socioeconomic-factor">Linear Model of Racial Disparities in Post-Graduation Earnings After Adding a Socioeconomic Factor</h2>
<section id="model-overview-1" class="level4">
<h4 class="anchored" data-anchor-id="model-overview-1">Model Overview:</h4>
<p>Adding variables that correspond to student’s socioeconomic factors may serve reduce the omitted variable bias and therefore, improve the model fit. In this model, the <code>Socioeconomic_Div</code> variable is added.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients, Standard Errors and p-values:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                           Estimate   Std. Error     Pr(&gt;|t|)
(Intercept)            8291.3762990 2.338776e+03 4.276828e-04
Num_White_Students       -0.5160260 8.194784e-02 6.453139e-10
Num_Black_Students        1.0077657 3.149137e-01 1.457336e-03
Num_Hispanic_Students     0.4133961 1.493422e-01 5.838906e-03
Num_Asian_Students        1.6253378 2.327069e-01 8.759377e-12
Social_Econ_Div       55968.0924256 3.519328e+03 1.040459e-46</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
R-squared:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Multiple R-squared: 0.4206275 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Adjusted R-squared: 0.4150673 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
F-statistic and p-value:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>F-statistic: 75.64976 on 5 and 521 DF, p-value: 1.559507e-59 </code></pre>
</div>
</div>
</section>
<section id="model-findings-1" class="level3">
<h3 class="anchored" data-anchor-id="model-findings-1">Model Findings</h3>
<p>The small p-value for Social_Econ_Div <em>(1.04e-46)</em> indicates that it is highly statistically significant, suggesting a very strong relationship between socioeconomic diversity and average mean earnings. Its inclusion substantially increases the Multiple R-squared value, from approximately 0.14 to 0.42. This indicates that the model’s ability to explain the variability in average earnings has improved significantly. The increase in R-squared confirms that <code>Social_Econ_Div</code> helps the model explain the data more accurately.</p>
<p>However, adding <code>Social_Econ_Div</code> to the linear regression model significantly changes the results because it is a highly influential variable in the dependent variable <code>Avg_Mean_earning</code>, according to the increasing R-squared. When <code>Social_Econ_Div</code>, which calculates the percent low income students under the federal Pell Grant, is introduced, it strongly correlates with average post-grad earnings. This new predictor changes the “explanatory responsibility” of the other variables in the model, causing their coefficients to shift significantly.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is shown that Social economic diversity is positively related average earnings, which means that schools that have more low income students tend to have lower earnings after graduating. Then, logically, adding this variable to the model will retain the same pattern. However, this variable <code>Social_Econ_Div</code> completely shifts the race variable.</p>
<p>A potential reason for this shift is <em>multicollinearity</em>, which occurs when predictors in a regression model are correlated with each other. Before adding <code>Social_Econ_Div</code>, the variables such as <code>Num_White_Students</code>, <code>Num_Black_Students</code>, and other race variables were indirectly capturing some of the effects of socioeconomic diversity because it was not explicitly included. When <code>Social_Econ_Div</code> is introduced, it absorbed much of the explanatory power that previously appeared to belong to the other predictor. This redistribution results in dramatic changes to their coefficients and results in changes in sign and magnitude.</p>
<p><a href="images/sat.png"></a></p>
</section>
</section>
<section id="a-second-dataset-what-does-the-sat-really-test" class="level2">
<h2 class="anchored" data-anchor-id="a-second-dataset-what-does-the-sat-really-test">A Second Dataset: What does the SAT really test?</h2>
<p>The data is sourced from the National Center of Education Statistics (NCES). It summarizes data from more than 25 surveys administered by NCES and other government agencies. The primary responsibility of Annual Reports is to produce the congressionally mandated <em>Condition of Education</em> to display data about various levels of education and labor force outcomes in the United States. It provides easy access to an array of education statistics, informing national policy-making decisions, the news media, and the general public.</p>
<p><em>The dataset can be accessed using the following <a href="https://nces.ed.gov/surveys/annualreports/">link</a>.</em></p>
<section id="relationship-between-sat-scores-and-post-grad-earnings" class="level4">
<h4 class="anchored" data-anchor-id="relationship-between-sat-scores-and-post-grad-earnings">Relationship Between SAT Scores and Post-Grad Earnings</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sat-scores-across-student-income-brackets" class="level4">
<h4 class="anchored" data-anchor-id="sat-scores-across-student-income-brackets">SAT Scores Across Student Income Brackets</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The data suggests that higher SAT scores are correlated to higher post-grad earnings. Naively then, perhaps this data indicates that SAT scores are accurate measures of a student’s intelligent levels, and thereby their future level of wealth attainment and overall success.</p>
<p>However, incorporating the new dataset into the analysis reveals a different picture: there is a clear relationship between student income level and SAT score. This analysis highlights the precariousness of data interpretation and potential dangerousness in failing to account for confounding factors. Notably, failing to take into account lack of resources as a potential indicator of low SAT scores leads to the assumptions that the SAT is an accurate metric for intelligence. It is important to keep this in mind when analyzing complex datasets, particularly because racial data is intricate, and racial bias may unknowingly permeate beneath the surface.</p>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD # Limitations One limitation of this model is the issue of multicollinearity, as evidenced by the significant coefficient shifts after adding the socioeconomic diversity variable <code>Social_Econ_Div</code>. This suggests that predictors like racial composition were previously capturing part of the socioeconomic effect, making it difficult to disentangle their individual contributions. Multicollinearity reduces the reliability of the coefficients, which can lead to unstable interpretations regarding the precise effect of each variable. ======= # Limitations: One limitation of this model is the potential issue of multicollinearity, as evidenced by the significant coefficient shifts after adding the socioeconomic diversity variable <code>Social_Econ_Div</code>. This suggests that predictors like racial composition were previously capturing part of the socioeconomic effect, making it difficult to disentangle their individual contributions. Multicollinearity reduces the reliability of the coefficients, which can lead to unstable interpretations regarding the precise effect of each variable. &gt;&gt;&gt;&gt;&gt;&gt;&gt; 70d56ea43ad102efd3ebd72414652a3d949bdca1</p>
<p>Another limitation is the simplicity of the model in its current form. While adding <code>Social_Econ_Div</code> improved the explanatory power (R-squared increased significantly), there are likely additional omitted variables—such as school funding, geographic location, or program types—that could further explain post-graduation earnings disparities. Additionally, this model assumes a linear relationship between predictors and earnings, which might oversimplify more complex, non-linear patterns in the data.</p>
<p>Lastly, this dataset categorizes race in its simplest form: White, Black, Asian, and Hispanic. More nuanced data-such as incorporating ethnicity and smaller racial groups-is necessary in drawing key conclusions about the complex racial dynamics in higher education.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>The initial model, which excludes socioeconomic diversity, reveals significant disparities in post-graduation earnings across racial groups. The coefficients suggest that, holding other factors constant, schools with higher numbers of Black and Hispanic students are associated with lower mean earnings, while schools with more Asian students show a strong positive association with earnings. Notably, the p-values for these coefficients indicate statistical significance, reinforcing that these disparities are unlikely to be due to random chance.</p>
<p>However, the relatively low R-squared value <em>(0.14)</em> in this model suggests that racial composition alone explains only a small portion of the variability in average earnings. This highlights that while racial disparities exist, other unobserved factors—such as socioeconomic diversity, school resources, or geographic differences—are likely influencing post-graduation outcomes. The negative coefficients for Black and Hispanic student numbers underscore systemic inequalities that may be linked to broader social and institutional challenges, which are not accounted for in this model.</p>
<p>The results of the second model demonstrate that socioeconomic diversity plays a crucial role in explaining variations in post-graduation earnings, significantly improving the model’s explanatory power when included. Its addition, however, highlights the potential challenge of multicollinearity and the redistribution of explanatory influence among variables, particularly racial composition. While the model provides valuable insights, further refinements—including additional variables and consideration of non-linear relationships—are necessary to fully capture the determinants of earnings disparities across different demographics.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sussmanbu\.github\.io\/ma-4615-fa24-final-project-group-3\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>