---
title: "Blog post1"
editor: visual
---

<https://www.washingtonpost.com/graphics/investigations/police-shootings-database/> The dataset identifies the date of the shooting, id, name, manner of death, whether the victim was armed, gender, race, city, state, signs of mental illness, and threat level. The Post began tracking details of police shootings in 2015 to 2022 in order to provide comprehensive information about fatal police shootings and to focus on police accountability nationwide.We hope to examine the relationship between race and police shootings, taking into account the confounding factors that may have influenced the shooting, including whether the victim was armed, whether they were undergoing a mental health crisis, and whether they were fleeing. We forsee challenges in fully understanding and representing the complexity of each situation, both because the data is not compreshensive to capture the true nature of the situation and because there may be bias. For example, categories such as "threat level" includes many "undetermined" and "other" data values, which does not provide any information about the threat the victim posed to others. And if "threat level" is determined by the perspective of the police officer involved in the shooting, they may be influenced to cite data values that more closely align with their views.

<https://collegescorecard.ed.gov/data/> This data has been collected by the US Department of Education to provide insight into the racial diversity and demographic composition of student bodies in various educational institutions. The dataset likely contains numerous columns related to various demographic data, including "ugds_white," "ugds_asian," and similar fields for other racial groups representing the percentage of undergraduate students belonging to different racial categories. The number of rows represents different institutions. One aspect would be using the data to find out how different racial groups, such as White, Asian, Hispanic, and Black students, compare across institutions. We could also research whether there are any significant trends over time or across geographic locations in terms of racial representation. The challenge for analyzing this dataset is that large datasets with mixed data types can slow down analysis and may require filtering or restructuring.

