---
title: "Blog post6"
subtitle: ""
author: "group 3"
date: "2024-11-11"
description: ""
image-alt: ""
categories: []
date-modified: "2024-11-11"
draft: false
---
```{r}
library(tidyverse)
library(dplyr)

education_cohort_combined_data1 <- read_rds("dataset/education_cohort_combined_data.rds")
str(education_cohort_combined_data1)
summary(education_cohort_combined_data1)
head(education_cohort_combined_data1)
```
```{r}
library(dplyr)
education_cohort_combined_data1 <- education_cohort_combined_data1 |>
  mutate(
    EARN_COUNT_WNE_5YR = as.numeric(EARN_COUNT_WNE_5YR)
  )

field_summary <- education_cohort_combined_data1 |>
  group_by(CIPDESC) |>
  summarise(
    Avg_Working_5YR = mean(EARN_COUNT_WNE_5YR, na.rm = TRUE),
    Total_Working_5YR = sum(EARN_COUNT_WNE_5YR, na.rm = TRUE),
    Count = n()
  ) |>
  arrange(desc(Total_Working_5YR))
```

```{r}
library(ggplot2)
top_fields <- field_summary |>
  top_n(20, Total_Working_5YR)
#Listing the fields of study with the highest employment outcomes in a descending order
ggplot(top_fields, aes(x = reorder(CIPDESC, -Total_Working_5YR), y = Total_Working_5YR)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Top Fields of Study by Employment Outcomes", x = "Field of Study", y = "Total Employed(5 yrs After Completion)")

#Have to use coord_flip() because otherwise the names of different fields of study will be overlapped with each other
```

