---
title: "Blog post1"
subtitle: ""
author: "group 3"
date: "2024-10-11"
description:  |
  This blog post details datasets that we initially researched.
# image: ""
image-alt: ""
categories: []
date-modified: "2024-10-11"
draft: false
editor: visual
---

<https://www.washingtonpost.com/graphics/investigations/police-shootings-database/> The dataset identifies the date of the shooting, id, name, manner of death, whether the victim was armed, gender, race, city, state, signs of mental illness, and threat level. The Post began tracking details of police shootings in 2015 to 2022 in order to provide comprehensive information about fatal police shootings and to focus on police accountability nationwide.We hope to examine the relationship between race and police shootings, taking into account the confounding factors that may have influenced the shooting, including whether the victim was armed, whether they were undergoing a mental health crisis, and whether they were fleeing. We forsee challenges in fully understanding and representing the complexity of each situation, both because the data is not comprehensive to capture the true nature of the situation and because there may be bias. For example, categories such as "threat level" includes many "undetermined" and "other" data values, which does not provide any information about the threat the victim posed to others. And if "threat level" is determined by the perspective of the police officer involved in the shooting, they may be influenced to cite data values that more closely align with their views.

<https://collegescorecard.ed.gov/data/> This data has been collected by the US Department of Education to provide insight into the racial diversity and demographic composition of student bodies in various educational institutions. The dataset likely contains numerous columns related to various demographic data, including "ugds_white," "ugds_asian," and similar fields for other racial groups representing the percentage of undergraduate students belonging to different racial categories. The number of rows represents different institutions. One aspect would be using the data to find out how different racial groups, such as White, Asian, Hispanic, and Black students, compare across institutions. We could also research whether there are any significant trends over time or across geographic locations in terms of racial representation. The challenge for analyzing this dataset is that large datasets with mixed data types can slow down analysis and may require filtering or restructuring.

[https://datacatalog.urban.org/dataset/racial-and-ethnic-representativeness-us-postsecondary-education-institutionshttps://datacatalog.urban.org/dataset/racial-and-ethnic-representativeness-us-postsecondary-education-institutions](https://datacatalog.urban.org/dataset/racial-and-ethnic-representativeness-us-postsecondary-education-institutions)

The dataset contains 17,267 rows and 34 columns. This data represents racial demographics and institutional characteristics of U.S. postsecondary education institutions. It was collected to analyze how closely colleges' racial and ethnic compositions reflect the demographics of their surrounding communities, using data from IPEDS and the U.S. Census. Cleaning the dataset will involve addressing missing values in columns related to specific racial groups. The main questions are around the extent at which institutions mirror regional diversity, as well as whether public, private, or selective institutions show larger disparities in representation. Some challenges include managing missing data, dealing with regional demographic variations, and developing accurate metrics to assess representativeness and equity.

<https://www.cdc.gov/nchs/data/nvsr/nvsr73/nvsr73-08.pdf> (page 9) This data by the U.S. Centers for Disease Control and Prevention (CDC) observes the death rates for the top 15 leading causes of death. It entails columns that not only present the percent change from the year 2020 to 2021, but also the ratio of races. For example, it provides the ratio of death rates for Black to White, Asian to White, Hispanic to White, etc. Such information is crucial for the healthcare system as it provides insight on health disparities across categories like illnesses, diseases, accidents, and other causes of death. This will allow for the implementation of prevention strategies by prioritizing certain health threats over others. Moreover, it will aid in future research focus, facilitate resource allocation, and raise public awareness, ultimately improving the healthcare system in the United States.

From this data, it is possible to determine which cause of death depicts the largest disparity among the racial ratios. Although I am able to view the dataset, due to the PDF format of this data, analyzing it would pose as a challenge because it may have to be manually copied onto another format. Furthermore the titles for some of the columns are a little inconsistent in terms of the ratio. For example, one column is “Black to White” and another is “White to Asian”; thus, the numbers on some of the columns may need to be inverted to ensure consistency and match the format of the others.

<https://www.census.gov/programs-surveys/ces/data/public-use-data/race-and-economic-opportunity-data-tables.html>

For this data, racial disparities in income and other outcomes are among the most visible and persistent features of American society. The sources of these disparities have been studied and debated for decades, with explanations ranging from residential segregation and discrimination to differences in family structure and genetics. Most previous work on racial disparities has studied inequality within a single generation of people.

(We will decide which three to choose to go on later.)
